web/router.ex
defmodule Flexcility.Router do
  use Flexcility.Web, :router
  use Passport

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :current_user
  end

	pipeline :no_layout do
		plug :put_layout, false
	end

  pipeline :set_menu do
    plug Flexcility.Plugs.MenuItems
  end

  pipeline :redirect_logged_in_user do
    plug Flexcility.Plugs.RedirectLoggedInUser
  end

  pipeline :authorize do
    plug Flexcility.Plugs.Authorize
  end

  pipeline :load_profile do
    plug Flexcility.Plug.LoadProfile
  end

  scope "/", Flexcility do
    pipe_through [:browser]
    get "/logout", SessionController, :delete
    get "/not_found", PageController, :subdomain_not_found
    get "/error", PageController, :error
  end

  scope "/", Flexcility do
    pipe_through [:browser, :set_menu, :authorize]
    resources "/profiles", ProfileController, only: [:new, :create]
  end

  scope "/", Flexcility do
    pipe_through [:browser, :redirect_logged_in_user]
    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/forget-password", PasswordController, :forget_password
    post "/reset-password", PasswordController, :reset_password
  end

  scope "/", Flexcility do
    pipe_through [:browser, :set_menu, :authorize, :load_profile] # Use the default browser stack

    get "/send_email_test", OrganisationController, :send_an_email
    resources "/organisations", OrganisationController do
      get "/manage", Organisation.ManagementController, :index
      scope "/manage" do
        resources "/traits", Organisation.TraitController, except: [:update, :create]
        put "/traits", Organisation.TraitController, :update
        get "/members", Organisation.ManagementController, :members
        resources "/sites", Organisation.SiteController do
          resources "/assets", Organisation.AssetController
        end
      end
    end
    resources "/sites", SiteController do
      resources "/assets", AssetController
      post "/invite_user", SiteController, :invite_user, as: :invite
    end
    resources "/requests", RequestController do
      get "/assign_technicians", RequestController, :assign_technicians, as: :assign_technicians
      post "/assign_technicians", RequestController, :create_technician_assignment, as: :assign_technicians
    end

    resources "/orders", OrderController do
      get "/assign_technicians", OrderController, :assign_technicians, as: :assign_technicians
      post "/assign_technicians", OrderController, :create_technician_assignment, as: :assign_technicians
    end
    resources "/reports", ReportController
    get "/profiles/edit", ProfileController, :edit
    resources "/profiles", ProfileController, except: [:index, :new, :create]
    resources "/invitations", InvitationController do
      get "/accept", InvitationController, :view_invite, as: :view
      post "/accept", InvitationController, :accept_invite, as: :accept
    end
  end


  scope "/api", Flexcility, as: :api do
    pipe_through [:api, :set_menu]
    resources "/organisations", Api.OrganisationController, only: [:create]
    resources "/sites", SiteController, only: [] do
      get "/assets", AssetController, :index
      resources "/assets", Api.AssetsController, except: [:new, :edit]
    end
    get "/subdomain_unique", OrganisationController, :subdomain_unique
  end

  if Mix.env == :dev do
  # If using Phoenix
  forward "/sent_emails", Bamboo.EmailPreviewPlug

end


  # Other scopes may use custom stacks.
  # scope "/api", Flexcility do
  #   pipe_through :api
  # end
end

web/subdomain_router.ex
defmodule Flexcility.SubdomainRouter do
  use Flexcility.Web, :router
  use Passport

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :current_user
    plug :put_layout, {Flexcility.LayoutView, :organisation_layout}
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :current_user
  end

  pipeline :no_layout do
    plug :put_layout, "none.html"
  end

  pipeline :set_menu do
    plug Flexcility.Plugs.MenuItems
  end

  pipeline :redirect_logged_in_user do
    plug Flexcility.Plugs.RedirectLoggedInUser
  end

  pipeline :authorize do
    plug Flexcility.Plugs.Authorize
    plug Flexcility.Plugs.AuthorizeForOrganisation
  end

  pipeline :load_profile do
    plug Flexcility.Plug.LoadProfile
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :authorize, :load_profile] # Use the default browser stack
    # get "/", DashboardController, :index
    get "/dashboard", DashboardController, :index
    get "/profile", ProfileController, :show
    put "/profile", ProfileController, :update
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :no_layout]
    get "/logout", SessionController, :delete
    get "/invitations/:invitation_key", InvitationController, :show
    post "/invitations/:invitation_key/accept", InvitationController, :accept
    post "/invitations/:invitation_key/reject", InvitationController, :reject
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :redirect_logged_in_user]
    get "/login", SessionController, :new
    get "/", SessionController, :new
    get "/login/:invitation_key", SessionController, :invitation
    post "/login", SessionController, :create
  end

  scope "/", Flexcility do
    pipe_through [:browser]
    get "/register", RegistrationController, :invitation
    post "/register", RegistrationController, :create
  end
  #
  # scope "/", Flexcility.Subdomain do
  #   pipe_through [:browser, :redirect_logged_in_user]
  #   get "/register", RegistrationController, :new
  #   post "/register", RegistrationController, :create
  #   get "/forget-password", PasswordController, :forget_password
  #   post "/reset-password", PasswordController, :reset_password
  # end



  # Other scopes may use custom stacks.
  # scope "/api", Flexcility do
  #   pipe_through :api
  # end
end

web/models/trait.ex
defmodule Flexcility.Trait do
  use Flexcility.Web, :model

  schema "traits" do
    field :name, :string
    field :code, :string
    field :abbreviation, :string

    timestamps()

    many_to_many :organisations, Flexcility.Organisation, join_through: "organisations_traits"
    many_to_many :sites, Flexcility.Site, join_through: "sites_traits"
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :code, :abbreviation])
    |> validate_required([:name, :code, :abbreviation])
  end

  @doc """
  Returns a list of Trait structs matching the list of ids given.
  """
  def all(ids) do
    query = from t in Flexcility.Trait,
      where: t.id in ^ids
    Repo.all(query)
  end
end

web/controllers/organisation/asset_controller.ex
defmodule Flexcility.Organisation.AssetController do
  use Flexcility.Web, :controller
  import Ecto.Query, only: [from: 2]
  alias Flexcility.Asset
  alias Flexcility.InstalledAsset
  plug Flexcility.Plugs.AssignOrganisation

  plug :scrub_params, "asset" when action in [:create, :update]
  plug :assign_project

  def index(conn, _params) do
    %{"site_id" => site_id} = conn.params
    site_id = String.to_integer(site_id)
    query = from a in Asset,
            join: p in assoc(a, :sites),
            where: p.id == ^site_id,
            preload: [sites: p]
    assets = Repo.all(query)

    render(conn, assets: assets, page_title: conn.assigns.organisation.name)
  end

  def new(conn, _params) do
    assets = Repo.all(Asset) |> Enum.map(&({"#{&1.name} - #{&1.model_id}", &1.id }))
    changeset = InstalledAsset.changeset(%InstalledAsset{})
    render(conn, "new.html", assets: assets, changeset: changeset, page_title: conn.assigns.organisation.name)
  end

  def create(conn, %{"asset" => asset_params}) do
    changeset = Asset.create_changeset(%Asset{}, conn.assigns.site.id, asset_params)

    case Repo.insert(changeset) do
      {:ok, asset} ->
        Asset.image_changeset(asset, asset_params)
        |> Repo.update
        conn
        |> put_flash(:info, "Asset created successfully.")
        |> redirect(to: organisation_site_asset_path(conn, :index, conn.assigns.organisation, conn.assigns.site))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, site_id: conn.assigns.site.id)
    end
  end

  def show(conn, %{"id" => id}) do
    asset = Repo.get!(Asset, id)
    render(conn, "show.html", asset: asset)
  end

  def edit(conn, %{"id" => id}) do
    asset = Repo.get!(Asset, id)
    changeset = Asset.changeset(asset)
    render(conn, "edit.html", asset: asset, changeset: changeset)
  end

  def update(conn, %{"id" => id, "asset" => asset_params}) do
    asset = Repo.get!(Asset, id)
    changeset = Asset.changeset(asset, asset_params)

    case Repo.update(changeset) do
      {:ok, asset} ->
        conn
        |> put_flash(:info, "Asset updated successfully.")
        |> redirect(to: organisation_site_asset_path(conn, :show, conn.assigns.organisation, conn.assigns.site.id, asset))
      {:error, changeset} ->
        render(conn, "edit.html", asset: asset, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    asset = Repo.get!(Asset, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(asset)

    conn
    |> put_flash(:info, "Asset deleted successfully.")
    |> redirect(to: organisation_site_asset_path(conn, :index, conn.assigns.organsation, conn.assigns.site.id))
  end

  def assign_project(conn, _opts) do
    %{params: %{"site_id" => site_id}} = conn
    project = Repo.get(Flexcility.Site, site_id)
    assign(conn, :site, project)
  end
end

web/controllers/organisation/management_controller.ex
defmodule Flexcility.Organisation.ManagementController do
  use Flexcility.Web, :controller

  alias Flexcility.Organisation

  def index(conn, %{"organisation_id" => id}) do
    organisation = Repo.get(Organisation, id)
    conn
    |> assign(:page_title, "Manage #{organisation.name}")
    |> render("index.html", organisation: organisation)
  end

  def members(conn, %{"organisation_id" => id}) do
    conn
    |> assign(:page_title, "Manage Members")
    |> render("members.html")
  end
end

web/controllers/organisation/site_controller.ex
defmodule Flexcility.Organisation.SiteController do
  use Flexcility.Web, :controller

  alias Flexcility.Site
  alias Flexcility.UsersRole
  alias Flexcility.Role
  alias Flexcility.User
  plug Flexcility.Plugs.AssignOrganisation
  import Ecto.Query, only: [from: 2]

  plug :scrub_params, "site" when action in [:create, :update]

  def index(
    %{assigns: %{current_user: current_user}}=conn, _params
  ) do
    organisation = conn.assigns.organisation
      |> Repo.preload([{:sites, [:assets]}])
    sites = organisation.sites
    render(conn, "index.html", sites: sites, page_title: "#{organisation.name}")
  end

  def invite_user(conn, %{
    "invite_user" => %{
      "user_email" => email,
      "user_role" => role_id
    },
    "site_id" => site_id
  }) do

    user = User |> Repo.get_by(email: email)
    site = Site |> Repo.get(site_id)
    role = Role |> Repo.get(role_id)
    user_id = case user do
      nil -> nil
      user -> user.id
    end
    users_role_changes= %{
      role_id: role.id, user_id: user_id, site_id: site.id
    }

    case user_id do
      nil ->
        conn
        |> put_flash(:error, "That user cannot be added to this site")
        |> redirect(to: organisation_site_path(conn, :show, conn.assigns.organisation.id, site))
      _ ->
        changeset = UsersRole.create_changeset(
          UsersRole,Repo, users_role_changes
        )

        case Repo.insert_or_update(changeset) do
          {:ok, _users_role} ->
            conn
            |> put_flash(:success, "Successfully invited #{email} as #{role.name}")
            |> redirect(to: organisation_site_path(conn, :show, conn.assigns.organisation.id, site))
          {:error, _changeset} ->
            conn
            |> put_flash(:error, "That user cannot be added to this site")
            |> redirect(to: organisation_site_path(conn, :show, conn.assigns.organisation.id, site))
        end
    end
  end

  def new(conn, _params) do
    changeset = Site.changeset(%Site{})
    render(conn, "new.html", changeset: changeset, conn: conn)
  end

  def create(conn, %{"site" => site_params}) do
    current_organisation = conn.assigns.organisation
    changeset = Site.create_changeset(%Site{}, site_params)
      |> Ecto.Changeset.put_assoc(:organisation, current_organisation)

    case Repo.insert(changeset) do
      {:ok, site} ->
        Site.image_changeset(site, site_params)
        |> Repo.update

        conn
        |> put_flash(:success, "Site created successfully.")
        |> redirect(to: organisation_site_path(conn, :show, conn.assigns.organisation.id, site))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    roles = Role |> Repo.all
    roles_select_list = roles |> Enum.map(fn x -> {"#{x.name}", x.id} end)
    site = Site |> Repo.get!(id) |> Repo.preload([:organisation, :assets])
    query = from ur in UsersRole,
            where: ur.site_id == ^site.id
    users_roles = Repo.all(query)
                  |> Repo.preload([:user, :site, :role])
    conn = conn |> assign(:page_title, site.name)
    render(conn, "show.html", site: site, roles_select_list: roles_select_list, site_members: users_roles, page_title: conn.assigns.organisation.name)
  end

  def edit(conn, %{"id" => id}) do
    site = Repo.get!(Site, id)
    changeset = Site.changeset(site)
    render(conn, "edit.html", site: site, changeset: changeset)
  end

  def update(conn, %{"id" => id, "site" => site_params}) do
    site = Repo.get!(Site, id)
    changeset = Site.changeset(site, site_params)

    case Repo.update(changeset) do
      {:ok, site} ->
        conn
        |> put_flash(:success, "Site updated successfully.")
        |> redirect(to: organisation_site_path(conn, :show, conn.assigns.organisation.id, site))
      {:error, changeset} ->
        render(conn, "edit.html", site: site, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    site = Repo.get!(Site, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(site)

    conn
    |> put_flash(:success, "Site deleted successfully.")
    |> redirect(to: organisation_site_path(conn, :index, conn.assigns.organisation.id))
  end
end

web/views/organisation/asset_view.ex
defmodule Flexcility.Organisation.AssetView do
  use Flexcility.Web, :view
  import Flexcility.LayoutView, only: [image: 1]

	def render("index.json", struct) do
    %{assets: assets} = struct
    assets = assets
      |> Enum.map(
          fn x ->
            Map.drop(x, [
              :__meta__, :__struct__, :site, :requests
            ])
          end
        )
    assets
  end
end

web/views/organisation/organisation_management_view.ex
defmodule Flexcility.Organisation.ManagementView do
  use Flexcility.Web, :view
end

web/views/organisation/site_view.ex
defmodule Flexcility.Organisation.SiteView do
  use Flexcility.Web, :view
  alias Flexcility.Repo
  import Flexcility.LayoutView, only: [display_name: 1,
                                        display_created_at: 1,
                                        image: 1, display_flash_message: 1]

  def project_members(project) do
    %{members: members} = project |> Repo.preload(members: [:roles])
    members |> Enum.map(fn m ->
      %{email: m.email, roles: Enum.map(m.roles, fn r ->
        %{name: r.name}
      end)}
    end )
  end

  def display_organisation_name(organisation) do
    organisation.name
  end

  def show_role_names(roles) do
    roles
    |> Enum.map(fn r -> r.name end)
    |> Enum.join(",")
  end

  def technician?(%{role: %{name: name}}) do
    name == "Technician"
  end

  def admin?(%{role: %{name: name}}) do
    name == "Admin"
  end

  def technicians(members) do
    members
    |> Enum.filter(&technician?/1)
  end

  def admins(members) do
    members
    |> Enum.filter(&admin?/1)
  end

  def asset_count(thing) do
    case thing do
      %Flexcility.Site{} ->
        thing.assets |> Enum.count
    end
  end


end

web/views/organisation/trait_view.ex
defmodule Flexcility.Organisation.TraitView do
  use Flexcility.Web, :view

  def display_organisation_trait_check(organisation, trait) do
    Enum.member?(organisation.traits, trait)
  end

  def display_organisation_facility_check(organisation, facility) do
    Enum.member?(organisation.facilities, facility)
  end
end

web/views/organisation_view.ex
defmodule Flexcility.OrganisationView do
  use Flexcility.Web, :view
  alias Flexcility.Organisation
  import Flexcility.LayoutView, only: [display_name: 1,
                                        display_created_at: 1,
                                        image: 1, thumb: 1]

  def get_members(organisation) do
    Organisation.get_members(organisation)
  end

  def render("subdomain_unique.json", %{subdomain_unique: subdomain_unique}) do
    subdomain_unique
  end
end

web/templates/organisation/trait/edit.html.eex
<h2>Edit trait</h2>

<%= render "form.html", changeset: @changeset,
                        action: organisation_trait_path(@conn, :update, @organisation.id, @trait) %>

<%= link "Back", to: organisation_trait_path(@conn, :index, @organisation.id) %>

web/templates/organisation/trait/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :code, class: "control-label" %>
    <%= text_input f, :code, class: "form-control" %>
    <%= error_tag f, :code %>
  </div>

  <div class="form-group">
    <%= label f, :abbreviation, class: "control-label" %>
    <%= text_input f, :abbreviation, class: "form-control" %>
    <%= error_tag f, :abbreviation %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/organisation/trait/index.html.eex
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="header">
            <h4 class="title">Assign Traits and Facilities</h4>
          </div>
          <div class="content">
            <%= form_for @changeset, @action, fn f-> %>
              <legend>Traits</legend>
              <span><small>Select the traits that apply to your sites/buildings</small></span>

              <fieldset>
              <div class="form-group">
                  <div class="col-sm-4" >
                    <%= for {trait,index} <- Enum.with_index(@traits) do %>
                      <%= if( rem(index,3) == 0 && index != 0 ) do %>
                        </div>
                        <div class="col-sm-4">
                      <% end %>
                      <label class="checkbox">
                        <%= checkbox(:organisation_traits, trait.id, "data-toggle": "checkbox", checked: display_organisation_trait_check(@organisation, trait)) %>
                          <%= trait.name %> (<%= trait.abbreviation %>)
                      </label>
                    <% end %>
                  </div>
              </div>
              </fieldset>
              <legend>Facilities</legend>
              <span><small>Select the types of facilities that your organisation manages. (Each site you define will fall under one of these facility types)</small></span>
              <fieldset>
              <div class="form-group">
                  <div class="col-sm-4" >
                    <%= for {facility,index} <- Enum.with_index(@facilities) do %>
                      <%= if( rem(index,3) == 0 && index != 0 ) do %>
                        </div>
                        <div class="col-sm-4">
                      <% end %>
                      <label class="checkbox">
                        <%= checkbox(:organisation_facilities, facility.id, "data-toggle": "checkbox", checked: display_organisation_facility_check(@organisation, facility)) %>
                        <%= facility.name %>
                      </label>
                    <% end %>
                  </div>
              </div>
              </fieldset>
              <fieldset>
              <div class="form-group pull-right">
                <%= link "Back", to: organisation_management_path(@conn, :index, @organisation.id), class: "btn btn-fill btn-secondary" %>
                <%= submit "Update", id: "organisation_trait_update_button", class: "btn btn-fill btn-primary" %>
              </div>
              </fieldset>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--//
<h2>Listing traits</h2>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Abbreviation</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for trait <- @traits do %>
    <tr>
      <td><%= trait.name %></td>
      <td><%= trait.code %></td>
      <td><%= trait.abbreviation %></td>

      <td class="text-right">
        <%= link "Show", to: organisation_trait_path(@conn, :show, @organisation.id, trait), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: organisation_trait_path(@conn, :edit, @organisation.id, trait), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: organisation_trait_path(@conn, :delete, @organisation.id, trait), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New trait", to: organisation_trait_path(@conn, :new, @organisation.id) %>
//-->

web/templates/organisation/trait/new.html.eex
<h2>New trait</h2>

<%= render "form.html", changeset: @changeset,
                        action: organisation_trait_path(@conn, :create, @organisation.id) %>

<%= link "Back", to: organisation_trait_path(@conn, :index, @organisation.id) %>

web/templates/organisation/trait/show.html.eex
<h2>Show trait</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @trait.name %>
  </li>

  <li>
    <strong>Code:</strong>
    <%= @trait.code %>
  </li>

  <li>
    <strong>Abbreviation:</strong>
    <%= @trait.abbreviation %>
  </li>

</ul>

<%= link "Edit", to: organisation_trait_path(@conn, :edit, @trait, @organisation.id) %>
<%= link "Back", to: organisation_trait_path(@conn, :index, @organisation.id) %>