web/router.ex
defmodule Flexcility.Router do
  use Flexcility.Web, :router
  use Passport

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :current_user
  end

	pipeline :no_layout do
		plug :put_layout, false
	end

  pipeline :set_menu do
    plug Flexcility.Plugs.MenuItems
  end

  pipeline :redirect_logged_in_user do
    plug Flexcility.Plugs.RedirectLoggedInUser
  end

  pipeline :authorize do
    plug Flexcility.Plugs.Authorize
  end

  pipeline :load_profile do
    plug Flexcility.Plug.LoadProfile
  end

  scope "/", Flexcility do
    pipe_through [:browser]
    get "/logout", SessionController, :delete
    get "/not_found", PageController, :subdomain_not_found
    get "/error", PageController, :error
  end

  scope "/", Flexcility do
    pipe_through [:browser, :set_menu, :authorize]
    resources "/profiles", ProfileController, only: [:new, :create]
  end

  scope "/", Flexcility do
    pipe_through [:browser, :redirect_logged_in_user]
    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/forget-password", PasswordController, :forget_password
    post "/reset-password", PasswordController, :reset_password
  end

  scope "/", Flexcility do
    pipe_through [:browser, :set_menu, :authorize, :load_profile] # Use the default browser stack

    get "/send_email_test", OrganisationController, :send_an_email
    resources "/organisations", OrganisationController do
      get "/manage", Organisation.ManagementController, :index
      scope "/manage" do
        resources "/traits", Organisation.TraitController, except: [:update, :create]
        put "/traits", Organisation.TraitController, :update
        get "/members", Organisation.ManagementController, :members
        resources "/sites", Organisation.SiteController do
          resources "/assets", Organisation.AssetController
        end
      end
    end
    resources "/sites", SiteController do
      resources "/assets", AssetController
      post "/invite_user", SiteController, :invite_user, as: :invite
    end
    resources "/requests", RequestController do
      get "/assign_technicians", RequestController, :assign_technicians, as: :assign_technicians
      post "/assign_technicians", RequestController, :create_technician_assignment, as: :assign_technicians
    end

    resources "/orders", OrderController do
      get "/assign_technicians", OrderController, :assign_technicians, as: :assign_technicians
      post "/assign_technicians", OrderController, :create_technician_assignment, as: :assign_technicians
    end
    resources "/reports", ReportController
    get "/profiles/edit", ProfileController, :edit
    resources "/profiles", ProfileController, except: [:index, :new, :create]
    resources "/invitations", InvitationController do
      get "/accept", InvitationController, :view_invite, as: :view
      post "/accept", InvitationController, :accept_invite, as: :accept
    end
  end


  scope "/api", Flexcility, as: :api do
    pipe_through [:api, :set_menu]
    resources "/organisations", Api.OrganisationController, only: [:create]
    resources "/sites", SiteController, only: [] do
      get "/assets", AssetController, :index
      resources "/assets", Api.AssetsController, except: [:new, :edit]
    end
    get "/subdomain_unique", OrganisationController, :subdomain_unique
  end

  if Mix.env == :dev do
  # If using Phoenix
  forward "/sent_emails", Bamboo.EmailPreviewPlug

end


  # Other scopes may use custom stacks.
  # scope "/api", Flexcility do
  #   pipe_through :api
  # end
end

web/subdomain_router.ex
defmodule Flexcility.SubdomainRouter do
  use Flexcility.Web, :router
  use Passport

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :current_user
    plug :put_layout, {Flexcility.LayoutView, :organisation_layout}
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :current_user
  end

  pipeline :no_layout do
    plug :put_layout, "none.html"
  end

  pipeline :set_menu do
    plug Flexcility.Plugs.MenuItems
  end

  pipeline :redirect_logged_in_user do
    plug Flexcility.Plugs.RedirectLoggedInUser
  end

  pipeline :authorize do
    plug Flexcility.Plugs.Authorize
    plug Flexcility.Plugs.AuthorizeForOrganisation
  end

  pipeline :load_profile do
    plug Flexcility.Plug.LoadProfile
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :authorize, :load_profile] # Use the default browser stack
    # get "/", DashboardController, :index
    get "/dashboard", DashboardController, :index
    get "/profile", ProfileController, :show
    put "/profile", ProfileController, :update
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :no_layout]
    get "/logout", SessionController, :delete
    get "/invitations/:invitation_key", InvitationController, :show
    post "/invitations/:invitation_key/accept", InvitationController, :accept
    post "/invitations/:invitation_key/reject", InvitationController, :reject
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :redirect_logged_in_user]
    get "/login", SessionController, :new
    get "/", SessionController, :new
    get "/login/:invitation_key", SessionController, :invitation
    post "/login", SessionController, :create
  end

  scope "/", Flexcility do
    pipe_through [:browser]
    get "/register", RegistrationController, :invitation
    post "/register", RegistrationController, :create
  end
  #
  # scope "/", Flexcility.Subdomain do
  #   pipe_through [:browser, :redirect_logged_in_user]
  #   get "/register", RegistrationController, :new
  #   post "/register", RegistrationController, :create
  #   get "/forget-password", PasswordController, :forget_password
  #   post "/reset-password", PasswordController, :reset_password
  # end



  # Other scopes may use custom stacks.
  # scope "/api", Flexcility do
  #   pipe_through :api
  # end
end

web/models/request.ex
defmodule Flexcility.Request do
  use Flexcility.Web, :model

  schema "requests" do
    field :worktype, :string
    field :title, :string
    field :location, :string
    field :description, :string
		field :instruction, :string
		field :type, :string
		field :priority, :string
		field :deadline, Ecto.DateTime

    belongs_to :user, Flexcility.User
		belongs_to :site, Flexcility.Site
		# belongs_to :asset, Flexcility.Asset

    has_many :assigned_technicians, Flexcility.AssignedTechnician, on_delete: :delete_all
		has_many :technicians, through: [:assigned_technicians, :user]
    has_many :orders, Flexcility.Order, on_delete: :delete_all

    timestamps
  end

  @required_fields ~w(title location description)
  @optional_fields ~w(site_id asset_id instruction worktype type priority deadline)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end

  def create_changeset(model, user_id, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> put_user_id(user_id)
  end

  def put_user_id(changeset, user_id) do
    case changeset do
      %Ecto.Changeset{valid?: true} ->
        put_change(changeset, :user_id, user_id)
      _ ->
        changeset
    end
  end

  def with_owner(query) do
    from q in query, preload: [:user]
  end
end

web/controllers/request_controller.ex
defmodule Flexcility.RequestController do
  use Flexcility.Web, :controller

  alias Flexcility.Request
  alias Flexcility.UsersRole
  alias Flexcility.AssignedTechnician

  plug :scrub_params, "request" when action in [:create, :update]
  plug :assign_project_params when action in [:edit]

  def index(
    %{assigns: %{
      assigned_requests: assigned_requests,
      current_user: current_user
      }
    }=conn, _params
  ) do
    requests = (current_user.requests ++ assigned_requests)
      |> Enum.uniq
      |> Repo.preload([:user])

    render(conn, "index.html", requests: requests)
  end

  def new(conn, params) do
    site_id = case params do
      %{"site_id" => id} -> String.to_integer id
      _ -> nil
    end
    changeset = Request.changeset(%Request{})
    render(conn, "new.html", changeset: changeset, site_id: site_id)
  end

  def create(conn, %{"request" => request_params}) do
    current_user = conn.assigns.current_user
    changeset = Request.create_changeset(%Request{}, current_user.id, request_params)
    %{"site_id" => site_id} = request_params

    case Repo.insert(changeset) do
      {:ok, _request} ->
        conn
        |> put_flash(:info, "Request created successfully.")
        |> redirect(to: request_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, site_id: site_id)
    end
  end

  def show(conn, %{"id" => id}) do
    request = Request
              |> Request.with_owner
              |> Repo.get!(id)
              |> Repo.preload([:site, :asset, :technicians,
                              {:site,
                                [:user,
                                {:users_roles, [:user, :role]}]}
                              ])
    render(conn, "show.html", request: request)
  end

  def edit(conn, %{"id" => id}) do
    request = Repo.get!(Request, id)
    changeset = Request.changeset(request)
    render(conn, "edit.html", request: request, changeset: changeset)
  end

  def update(conn, %{"id" => id, "request" => request_params}) do
    request = Repo.get!(Request, id)
    changeset = Request.changeset(request, request_params)

    case Repo.update(changeset) do
      {:ok, request} ->
        conn
        |> put_flash(:info, "Request updated successfully.")
        |> redirect(to: request_path(conn, :show, request))
      {:error, changeset} ->
        render(conn, "edit.html", request: request, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    request = Repo.get!(Request, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(request)

    conn
    |> put_flash(:info, "Request deleted successfully.")
    |> redirect(to: request_path(conn, :index))
  end

  def assign_project_params(conn, %{"site_id" => nil}) do
    conn
    |> assign(:site_id, nil)
  end

  def assign_project_params(conn, %{"site_id" => site_id}) do
    conn
    |> assign(:site_id, site_id)
  end

  def assign_project_params(conn, _params) do
    conn
    |> assign(:site_id, nil)
  end

  def assign_technicians(conn, %{"request_id" => request_id}) do
    request = Request
              |> Repo.get(request_id)
              |> Repo.preload([:site, :asset, :technicians])

    technicians = UsersRole
                  |> UsersRole.only_technicians
                  |> Repo.all(site_id: request.site.id)

    conn
    |> render("assign_technicians.html",
               request_id: request_id,
               request: request,
               available_technicians: technicians)
  end

  def create_technician_assignment(conn,
   %{"create_assigned_technicians" => technician_checkboxes,
      "request_id" => request_id }) do

    technicians_added = run_transaction(technician_checkboxes, request_id)

    case technicians_added do
      {:ok, _changes} ->
        conn
        |> put_flash(:info, "Successfully assigned technicians")
        |> redirect(to: request_path(conn, :show, request_id))
      {:error, _} ->
        conn
        |> put_flash(:error, "Something went wrong")
        |> redirect(to: request_path(conn, :assign_technicians, request_id))
    end
  end

  @doc """
  Runs transactions to add or remove assignment of technicians to a request.
  The technician_checkboxes are from the params for the assign technician
  form. They come in the shape
      ```
      Parameters: %{"create_assigned_technicians" =>
                      %{"12" => "true", "3" => "false"}, "request_id" => "9"}
      ```
  where the integer in the key portion of the key value pairs (i.e. "12" & "3")
  are the user ids of the technicians that are to be acted upon, and the value
  portion (true/false) represents if the checkbox was ticked or not.

  For true values, we insert the user_id and request_id into AssignedTechnician.
  For false, we delete entries with the user_id and request_id
  """
  def run_transaction(technician_checkboxes, request_id) do
    request_id = String.to_integer(request_id)

    Repo.transaction(fn ->
         technician_checkboxes
          |> Enum.map(fn {user_id, checked} ->
                case checked do
                  "true" ->
                    insert_technician_assignment(user_id, request_id)
                  "false" ->
                    remove_technician_assignment(user_id, request_id)
                end
              end)
          end)
  end

  def insert_technician_assignment(user_id, request_id) do
    assignment_params = [user_id: user_id, request_id: request_id]

    case Repo.get_by(AssignedTechnician, assignment_params) do
      nil -> %AssignedTechnician{}
      assigned_technician -> assigned_technician
    end
    |> AssignedTechnician.changeset(%{user_id: user_id, request_id: request_id})
    |> Repo.insert_or_update
  end

  def remove_technician_assignment(user_id, request_id) do
    assignment_params = [user_id: user_id, request_id: request_id]

    case Repo.get_by(AssignedTechnician, assignment_params) do
      nil -> nil# If we didn't find one, we don't do anything
      assigned_technician -> Repo.delete!(assigned_technician)
    end
  end
end

web/views/request_view.ex
defmodule Flexcility.RequestView do
  use Flexcility.Web, :view
  alias Flexcility.Repo
  import Flexcility.LayoutView, only: [display_name: 1, image: 1, profile_image: 1]

  def project_list(user) do
    all_sites(user)
    |> Enum.uniq
    |> Enum.map(fn x -> {x.name, x.id} end)
  end

  def asset_list(_user, nil) do
    []
  end

  def asset_list(user, site_id) do
    selected_project = all_sites(user)
      |> Enum.find(fn project -> project.id == site_id end)
      |> Repo.preload(:assets)

    selected_project.assets
    |> Enum.map(fn x -> {x.name, x.id} end)
  end


  def all_sites(user) do
    user.attached_sites ++ user.sites
  end

  def project_name(nil) do
    "N/A"
  end

  def project_name(project) do
    project.name
  end

  def asset_name(nil) do
    "N/A"
  end

  def asset_name(asset) do
    "#{asset.name} - #{asset.model_id}"
  end

# Takes a users_roles struct that has role.name = "Admin" and returns
# %{user: <the matched user>, role: "Admin"}
def admins(%{role: %{name: "Admin"}, user: admin}) do
    %{user: admin, role: "Admin"}
end

def admins(_) do
  []
end

def technicians(technician) do
    %{user: technician, role: "Technician"}
end

def technicians(_) do
  []
end

@doc ~S"""
Returns a map of users and roles, grouped by user.
Looks like this:
 %{<user A> => [%{user: <user A>, role: "Admin"}],
   <User B> => [%{user: <User B>, role: "Admin"},
                %{user: <User B>, role: "Technician"}],
   <User C> => [%{user: <User C, role: "Client"}]
   ... and so on
  }


  Note: a fully preloaded user struct with no associations looks like this:
  %Flexcility.User{__meta__: #Ecto.Schema.Metadata<:loaded>,
   assigned_orders: [],
   assigned_requests: []>,
   assigned_technicians: [],
   attached_sites: [],
   email: "fadhil@jomcode.com", first_name: "Fadhil", id: 3,
   inserted_at: #Ecto.DateTime<2016-07-26T15:56:24Z>, last_name: "Luqman",
   orders: []>,
   password: nil, password_confirmation: nil,
   password_hash: "$2b$12$3kX9.T4nOinKtD6buN0G8.N2YCQXmBfDa.gJSlLjNrE8iZDLnUzzq",
   sites: []>,
   reports: [],
   requests: [],
   roles: [],
   updated_at: #Ecto.DateTime<2016-07-28T04:12:06Z>,
   users_roles: []}
"""
def members_and_roles(%{user: owner,
                        technicians: assigned_technicians,
                        site: %{
                            user: project_owner,
                            users_roles: project_roles                            }
                        }) do # Here we match an order that's been preloaded
                            # with these associations

  # Calls `admins` from above to get a list of admins and roles,
  # i.e. [%{user: <admin struct>, role: "Admin"}]
  admins_with_roles = project_roles
                      |> Enum.map(&admins/1)

  # Calls `technicians` to get a  list of technicians and roles,
  # i.e. [%{user: <admin struct>, role: "Technician"}]
  technicians_with_roles = assigned_technicians
                           |> Enum.map(&technicians/1)

  # Now we put them together and flatten them, and then group by user struct
  members = [admins_with_roles,
              %{user: owner, role: "Requestor"},
              %{user: project_owner, role: "Site Owner"},
              technicians_with_roles
            ]
            |> List.flatten
            |> Enum.group_by(fn m -> m.user end)
end

# Gets a list or user and roles,
#  e.g. [{user: <user A>, role: "Admin"},
#        {user: <user A>, role: "Technician"}]
# and returns all the roles in a comma separated list, e.g. "Admin, Technician"
def display_roles(member_roles) do
  member_roles
  |> Enum.map(fn mr -> mr.role end)
  |> Enum.join(",")
end

end

web/templates/request/assign_technicians.html.eex
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox-content">
        <div class="ibox-title">
          <h5>Assign Technicians for Request ID: <%= @request.id %>
          <p><small><%= @request.title %><br/>
          <%= project_name(@request.site) %> - <%= asset_name(@request.asset) %></small></p></h5>
        </div>
        <br/><hr>
        <div class="form-group">
          <%= form_for @conn, request_assign_technicians_path(@conn, :assign_technicians, @request.id),
           [as: :create_assigned_technicians], fn f -> %>
          <% assigned_technician_ids = @request.technicians
                                  |> Enum.map(fn x -> x.id end) %>
                                  <%= for technician <- @available_technicians do %>
                                  <% checked = assigned_technician_ids |> Enum.member?(technician.user.id) %>
          <div class="i-checks"><label><%= checkbox f, :"#{technician.user.id}", checked: checked %><i></i> <%= technician.user.email %></label>
          </div>
          <% end %>
        </div>

        <div class="form-group">
          <%= submit "Submit", class: "btn btn-primary btn-rounded" %>
          <%= link "Back", to: request_path(@conn, :index), class: "btn btn-default btn-outline btn-rounded" %>
        </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

web/templates/request/edit.html.eex
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Edit Request <small></small></h5>
        </div>
          <%= render "form.html", changeset: @changeset,
            action: request_path(@conn, :update, @request),
            current_user: @conn.assigns.current_user,
            conn: @conn,
            site_id: @conn.assigns.site_id %>
      </div>
    </div>
  </div>
</div>

web/templates/request/form.html.eex
<div class="ibox-content">
  <%= form_for @changeset, @action, [multipart: true, class: "form-horizontal"], fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
    <% end %>

    <div class="form-group">
      <%= label f, :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_input f, :title, class: "form-control" %>
        <span class="error-tag">
          <%= error_tag f, :title %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, "Site", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= select f, :site_id, project_list(@current_user),
        prompt: "Choose A Site/Site", selected: @site_id ,
        class: "form-control" %>
        <span class="error-tag">
          <%= error_tag f, :site_id %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, "Asset", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= select f, :asset_id, asset_list(@current_user, @site_id), class: "form-control" %>
        <span, class="error-tag">
          <%= error_tag f, :asset_id%>
        </span>
      </div>
    </div>

    <script>
      $('#request_site_id').on("change", function(e) {
        e.preventDefault();
        selected_value = $('#request_site_id').val();

        $.ajax({
          url: "/api/sites/" + selected_value + "/assets",
          type: "GET",
          success: function(data) {
            $('#request_asset_id').empty();
            $.each(data, function(id, asset){
              $('#request_asset_id')
                .append("<option value="+ asset.id + ">"+ asset.name + "</option>");
              console.log(asset);
            })
          }
        })
      })
    </script>

    <div class="form-group">
      <%= label f, :location, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_input f, :location, class: "form-control" %>
        <span class="error-tag">
          <%= error_tag f, :location %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= textarea f, :description, class: "form-control" %>
        <span class="error-tag">
          <%= error_tag f, :description %>
        </span>
      </div>
    </div>

    <div class="hr-line-dashed">
    </div>

    <div class="form-group">
      <div class="col-sm-4 col-sm-offset-2">
        <%= submit "Submit", class: "btn btn-primary btn-rounded" %>
        <%= link "Back", to: request_path(@conn, :index), class: "btn btn-default btn-outline btn-rounded" %>
      </div>
    </div>
        <% end %>
</div>

web/templates/request/index.html.eex
<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInUp">
      <div class="ibox">
        <div class="ibox-title">
          <h2>Work Requests</h2><h5>Assigned to <%= display_name(@current_user) %></h5>
          <div class="ibox-tools">
            <%= link "Create New Request", to: request_path(@conn, :new), class: "btn btn-success btn-rounded btn-outline btn-sm" %>
          </div>
        </div>
      <div class="ibox-content">
        <div class="project-list">
          <table class="table table-hover">
            <tbody>
              <%= for request <- @requests do %>
                <%= link to: request_path(@conn, :show, request) do %>
                  <tr>
                    <td class="project-title">
                      <span><%= project_name(request.site) %></span><!-- Reserve for request_id -->
                    </td>
                    <td class="project-status">
                      <span class="label label-success label-outline"><%= request.id %></span><!-- Reserve for request_id -->
                    </td>
                    <td class="project-title">
                      <a href="<%= request_path(@conn, :show, request) %>"><%= request.title %>
                      <br/>
                      <small class="created-on">By <%= display_name(request.user) %> on <%= request.inserted_at %></small>
                      </a>
                    </td>
                    <td class="hidden-xs"><%= asset_name(request.asset) %></td>
                    <td class="hidden-xs"><%= request.location %></td>
                    <td class="hidden-xs"><%= request.description %></td>
                    <td class="project-people">
                      <a href=""><img alt="image" class="img-circle" src="img/a3.jpg"></a>
                      <a href=""><img alt="image" class="img-circle" src="img/a1.jpg"></a>
                      <a href=""><img alt="image" class="img-circle" src="img/a2.jpg"></a>
                      <a href=""><img alt="image" class="img-circle" src="img/a4.jpg"></a>
                      <a href=""><img alt="image" class="img-circle" src="img/a5.jpg"></a>
                    </td>
                    <td class="project-actions">
                      <%= link to: request_path(@conn, :show, request), class: "btn btn-white btn-rounded btn-sm" do %>
                        <i class="fa fa-folder"></i> View </a>
                      <% end %>
                    </td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div> <!-- End ibox-content -->
      </div>
    </div> <!-- End wrapper -->
  </div> <!-- End col -->
</div> <!-- End row -->

web/templates/request/new.html.eex
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Create A New Request <small></small></h5>
        </div>
        <%= render "form.html", changeset: @changeset,
            action: request_path(@conn, :create),
            current_user: @conn.assigns.current_user,
            site_id: @site_id,
            conn: @conn %>
      </div>
    </div>
  </div>
</div>