web/router.ex
defmodule Flexcility.Router do
  use Flexcility.Web, :router
  use Passport

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :current_user
  end

	pipeline :no_layout do
		plug :put_layout, false
	end

  pipeline :set_menu do
    plug Flexcility.Plugs.MenuItems
  end

  pipeline :redirect_logged_in_user do
    plug Flexcility.Plugs.RedirectLoggedInUser
  end

  pipeline :authorize do
    plug Flexcility.Plugs.Authorize
  end

  pipeline :load_profile do
    plug Flexcility.Plug.LoadProfile
  end

  scope "/", Flexcility do
    pipe_through [:browser]
    get "/logout", SessionController, :delete
    get "/not_found", PageController, :subdomain_not_found
    get "/error", PageController, :error
  end

  scope "/", Flexcility do
    pipe_through [:browser, :set_menu, :authorize]
    resources "/profiles", ProfileController, only: [:new, :create]
  end

  scope "/", Flexcility do
    pipe_through [:browser, :redirect_logged_in_user]
    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/forget-password", PasswordController, :forget_password
    post "/reset-password", PasswordController, :reset_password
  end

  scope "/", Flexcility do
    pipe_through [:browser, :set_menu, :authorize, :load_profile] # Use the default browser stack

    get "/send_email_test", OrganisationController, :send_an_email
    resources "/organisations", OrganisationController do
      get "/manage", Organisation.ManagementController, :index
      scope "/manage" do
        resources "/traits", Organisation.TraitController, except: [:update, :create]
        put "/traits", Organisation.TraitController, :update
        get "/members", Organisation.ManagementController, :members
        resources "/sites", Organisation.SiteController do
          resources "/assets", Organisation.AssetController
        end
      end
    end
    resources "/sites", SiteController do
      resources "/assets", AssetController
      post "/invite_user", SiteController, :invite_user, as: :invite
    end
    resources "/requests", RequestController do
      get "/assign_technicians", RequestController, :assign_technicians, as: :assign_technicians
      post "/assign_technicians", RequestController, :create_technician_assignment, as: :assign_technicians
    end

    resources "/orders", OrderController do
      get "/assign_technicians", OrderController, :assign_technicians, as: :assign_technicians
      post "/assign_technicians", OrderController, :create_technician_assignment, as: :assign_technicians
    end
    resources "/reports", ReportController
    get "/profiles/edit", ProfileController, :edit
    resources "/profiles", ProfileController, except: [:index, :new, :create]
    resources "/invitations", InvitationController do
      get "/accept", InvitationController, :view_invite, as: :view
      post "/accept", InvitationController, :accept_invite, as: :accept
    end
  end


  scope "/api", Flexcility, as: :api do
    pipe_through [:api, :set_menu]
    resources "/organisations", Api.OrganisationController, only: [:create]
    resources "/sites", SiteController, only: [] do
      get "/assets", AssetController, :index
      resources "/assets", Api.AssetsController, except: [:new, :edit]
    end
    get "/subdomain_unique", OrganisationController, :subdomain_unique
  end

  if Mix.env == :dev do
  # If using Phoenix
  forward "/sent_emails", Bamboo.EmailPreviewPlug

end


  # Other scopes may use custom stacks.
  # scope "/api", Flexcility do
  #   pipe_through :api
  # end
end

web/subdomain_router.ex
defmodule Flexcility.SubdomainRouter do
  use Flexcility.Web, :router
  use Passport

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :current_user
    plug :put_layout, {Flexcility.LayoutView, :organisation_layout}
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :current_user
  end

  pipeline :no_layout do
    plug :put_layout, "none.html"
  end

  pipeline :set_menu do
    plug Flexcility.Plugs.MenuItems
  end

  pipeline :redirect_logged_in_user do
    plug Flexcility.Plugs.RedirectLoggedInUser
  end

  pipeline :authorize do
    plug Flexcility.Plugs.Authorize
    plug Flexcility.Plugs.AuthorizeForOrganisation
  end

  pipeline :load_profile do
    plug Flexcility.Plug.LoadProfile
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :authorize, :load_profile] # Use the default browser stack
    # get "/", DashboardController, :index
    get "/dashboard", DashboardController, :index
    get "/profile", ProfileController, :show
    put "/profile", ProfileController, :update
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :no_layout]
    get "/logout", SessionController, :delete
    get "/invitations/:invitation_key", InvitationController, :show
    post "/invitations/:invitation_key/accept", InvitationController, :accept
    post "/invitations/:invitation_key/reject", InvitationController, :reject
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :redirect_logged_in_user]
    get "/login", SessionController, :new
    get "/", SessionController, :new
    get "/login/:invitation_key", SessionController, :invitation
    post "/login", SessionController, :create
  end

  scope "/", Flexcility do
    pipe_through [:browser]
    get "/register", RegistrationController, :invitation
    post "/register", RegistrationController, :create
  end
  #
  # scope "/", Flexcility.Subdomain do
  #   pipe_through [:browser, :redirect_logged_in_user]
  #   get "/register", RegistrationController, :new
  #   post "/register", RegistrationController, :create
  #   get "/forget-password", PasswordController, :forget_password
  #   post "/reset-password", PasswordController, :reset_password
  # end



  # Other scopes may use custom stacks.
  # scope "/api", Flexcility do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Flexcility.LayoutView do
  use Flexcility.Web, :view
  import Flexcility.Utils.PageTitle
  alias Flexcility.Image
  use Timex
  require Logger
  def display_name(user) do
    case user do
      %{first_name: first_name, last_name: last_name}
        when first_name != "" or last_name != "" ->
          String.trim("#{first_name} #{last_name}")
      %{email: email} ->
        email
      _ -> "Flex User"
    end
  end


  def display_nickname(user) do
    case user.profile do
      nil ->
        nil
      profile ->
        full_name = display_name(user)
        case profile.full_name do
          nil ->
            nil
          ^full_name ->
            profile.full_name
          nickname ->
            nickname
        end
    end
  end

  def display_created_at(object) do
    case object do
      %{inserted_at: inserted_at} ->
        Timex.format!(object.inserted_at, "%d/%m/%Y", :strftime)

    end
  end

  def display_flash_message(flash_message) when map_size(flash_message) > 0 do
    case flash_message do
      %{"success" => value} ->
        build_notify_js("success", value)
      %{"info" => value} ->
        build_notify_js("info", value)
        |> raw
      %{"error" => value} ->
        build_notify_js("danger", value)
        |> raw
      %{"warning" => value} ->
        build_notify_js("warning", value)
        |> raw
    end

  end

  def display_flash_message(%{}) do
    nil
  end

  def build_notify_js(flash_type, value) do
    """
      $.notify({
        message: '#{value}'
      },{
          type: '#{flash_type}',
          delay: 2000,
          placement: {
            align: 'center'
          }
      });
    """
    |> raw
  end



  def image(%{image: nil} ) do
    "/images/default-image.jpg"
  end

  def image(%{photo: nil} ) do
    "/images/default-image.jpg"
  end

  def image(%{photo: image} = thing) do
    Image.url({image, thing})
  end

  def image(%{image: image} = thing) do
    Flexcility.Image.url({thing.image, thing})
  end

  def image(%{logo: image} = thing) do
    Flexcility.Image.url({thing.logo, thing})
  end

  def thumb(%{image: nil}) do
    "/images/default_profile_picture.png"
  end

  def thumb(%{image: image} = thing) do
    Flexcility.Image.url({thing.image, thing}, :thumb)
  end

  def thumb(%{logo: image} = thing) do
    Flexcility.Image.url({thing.logo, thing}, :logo)
  end

  def image(params) do
    "/images/default-image.png"
  end

  def thumb(params) do
    "/images/default_profile_picture.png"
  end

  def profile_image(_) do
    "/images/default_profile_picture.png"
  end


  def display_invited_role(role) do
    case role.name do
      "Helpdesk" ->
        "As a Helpdesk User"
      "Technician" ->
        "As a Technician"
      "Engineer" ->
        "As an Engineer"
      "Admin" ->
        "As an Admin"
    end
  end
end

web/templates/layout/action_bar.html.eex
					<div class="row wrapper border-bottom white-bg page-heading">
							<div class="col-sm-4">
                <h2><%= page_title(@conn) %></h2>
									<%#= link "Flexcility", to: page_path(@conn, :index) %>
									<!-- <ol class="breadcrumb">
											<li>
													<a href="index.html">This is</a>
											</li>
											<li class="active">
													<strong>Breadcrumb</strong>
											</li>
									</ol> -->
							</div>
							<!-- <div class="col-sm-8">
									<div class="title-action">
											<a href="" class="btn btn-primary">This is action area</a>
									</div>
							</div> -->
					</div>

web/templates/layout/app.html.eex
<!doctype html>
<html lang="en">
 <%= render Flexcility.LayoutView, "header.html", assigns %>
<body>
	<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
	<script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
	<div class="wrapper">

		<!--// The menu bar on the left -->
		<%= render Flexcility.LayoutView, "sidebar.html", assigns %>

		<!--// The Main Panel (Exclusing the entire left menu bar -->
    <div class="main-panel">

			<!--// The top bar with the menu minimize button , search bar and
			notifications and Logout -->
			<%= render Flexcility.LayoutView, "top_navbar.html", assigns %>

      <!--// Template content -->
      <div class="content">
        <div class="container-fluid">
          <%= render @view_module, @view_template, assigns %>
        </div> <!-- End col -->

        <!--// Footer -->
        <%= render Flexcility.LayoutView, "footer.html", assigns %>
      </div> <!-- End row -->
    </div>
	</div>
</body>


<!--  Google Maps Plugin    -->
<!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script> -->

</html>

web/templates/layout/footer.html.eex
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>

                <li>
                    <a href="http://www.flexcility.com">
                        Flexcility.com
                    </a>
                </li>
                <!-- <li>
                    <a href="http://jomcod.com/fadhil">
                       Blog
                    </a>
                </li> -->
                <!-- <li>
                    <a href="http://www.creative-tim.com/license">
                        Licenses
                    </a>
                </li> -->
            </ul>
        </nav>
        <div class="copyright pull-right">
            &copy; <script>document.write(new Date().getFullYear())</script>, <a href="http://www.flexcility.com">Flexcility Systems Sdn Bhd</a>
        </div>
    </div>
</footer>
<script type="text/javascript">
  <% flash = get_flash(@conn) %>

  $(document).ready(function(){
    <%= display_flash_message(flash) %>
  });


</script>

web/templates/layout/header.html.eex
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>Flexcility | Facilities Management</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <meta name="viewport" content="width=device-width" />

  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
	<link rel="stylesheet" href="<%= static_path(@conn, "/css/vendor.css") %>">
	<link rel="icon" type="image/png" href="<%= static_path(@conn, "/images/favicon.png") %>">

  <!--  Fonts and icons     -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
  <!-- <link href="<%= static_path(@conn, "/css/themify-icons.css") %>" rel="stylesheet"> -->

  <meta name="description" content="An integrated Facilities Management App">
  <meta name="author" content="co-authored by Fadhil Luqman and Faruq Luqman">


</head>

web/templates/layout/invitation_card.html.eex
<div class="invitation-card card">
  <div class="header">
    <h4 class="title">You were invited by:</h4>
  </div>
  <div class="invitation-card-content content">
    <div class="row">
      <div class="col-xs-3">
          <img src="<%= thumb(@invitation.inviter.profile)%>" class="img-circle img-no-padding img-responsive" alt="Inviter Profile">

      </div>
      <div class="col-xs-8">
        <div class="inviter-email-display">
          <h4><%= @invitation.inviter.email %></h4>
        </div>
      </div>
    </div>
    <div class="row text-center">
      <h5>to join</h5>
    </div>
    <div class="row">
      <div class="col-xs-3">
        <img src="<%= thumb(@invitation.organisation)%>" class="img-responsive" alt="Organisation Logo">
      </div>
      <div class="col-xs-8">
        <div class="inviter-organisation-display">
          <h4><%= @invitation.organisation.name %></h4>
        </div>
      </div>
    </div>
    <div class="row text-center">
      <h4><%= display_invited_role(@invitation.role) %></h4>
    </div>
  </div>
  <div class="footer text-center">
    <small>Login or register to be assigned <%= String.downcase(display_invited_role(@invitation.role)) %> in <%= @invitation.organisation.name %></small>
  </div>
</div>

web/templates/layout/metis_menu.html.eex
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element"> <span>
                            <span style="display: none" id="user-hidden-id"><%= @current_user.id %></span>
                            <a href="<%= profile_path(@conn, :edit) %>">
                              <img id="user-display-image" alt="image"
                                class="img-circle profile-img-circle"
                                src="<%= thumb(@current_user.profile)%>" />
                            </a>
                             </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                          <span class="clear"> <span class="block m-t-xs"> <strong id="user-display-name" class="font-bold"><%= display_name(@current_user) %></strong>
                             </span> <span class="text-muted text-xs block">Developer<b class="caret"></b></span> </span> </a>
                        <ul class="dropdown-menu animated fadeInDown m-t-xs">
                            <li><a href="profile.html">Profile</a></li>
                            <li><a href="contacts.html">Contacts</a></li>
                            <li><a href="mailbox.html">Mailbox</a></li>
                            <li><%= link "Create Organisation", to: organisation_path(@conn, :new) %></li>
                        </ul>
                    </div>
                    <div class="logo-element">
                        IN+
                    </div>
                </li>
                <!-- <%#= if(@own_sites || @attached_sites) do %>
                  <li>
                      <a href=""><i class="fa fa-industry"></i> <span class="nav-label">Sites</span><span class="fa arrow"></span></a>
                      <ul class="nav nav-second-level collapse">
                        <%#= case @own_sites do %>
                          <%#= [] -> %>
                            <li>
                              <a href="<%#= site_path(@conn, :new) %>">New Site</a></li>
                            </li>
                          <%#=  _ -> %>
                            <li>
                              <a href="<%#= site_path(@conn, :index) %>">All Sites</a></li>
                            </li>
                            <li>
                              <a href="#">Own Sites<span class="fa arrow"></span></a>
                              <ul class="nav nav-third-level collapse in">
                            <%#= for mi <- @own_sites do %>
                              <li>
                                <%#= link mi.name, to: site_path(@conn, :show, mi.id) %>
                              </li>
                            <%# end %>
                              </ul>
                          </li>
                        <%# end %>
                        <%#= case @attached_sites do %>
                          <%#= [] -> %>
                          <%#=  _ -> %>
                            <li>
                              <a href="#">Assigned Sites<span class="fa arrow"></span></a>
                              <ul class="nav nav-third-level collapse in">
                            <%#= for mi <- @attached_sites do %>
                              <li>
                                <%#= link mi.name, to: site_path(@conn, :show, mi.id) %>
                              </li>
                            <%# end %>
                              </ul>
                          </li>
                        <%# end %>
                      </ul>
                  </li>
                <%# end %> -->
                <li>
                  <a href="<%= organisation_path(@conn, :index) %>"><i class="fa fa-home"></i> <span class="new-label">Your Organisations</span></a>
                </li>
                <li>
                  <a href="<%= request_path(@conn, :new) %>"><i class="fa fa-flash"></i> <span class="new-label">New Work Request</span></a>
                </li>

                <li>
                  <a href="<%= request_path(@conn, :index) %>"><i class="fa fa-eye"></i> <span class="new-label">View Work Requests</span></a>
                </li>

                <li>
                  <a href="<%= order_path(@conn, :index)%>"><i class="fa fa-wrench"></i> <span class="nav-label">View Work Orders</span></a>
                </li>

                <li>
                  <a href="<%= report_path(@conn, :index)%>"><i class="fa fa-file-text-o"></i> <span class="nav-label">View Work Reports</span></a>
                </li>

                <li>
<!--                    <a href="#"><i class="fa fa-sitemap"></i> <span class="nav-label">Menu Levels </span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li>
                            <a href="#">Third Level <span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>

                            </ul>
                        </li>
                        <li><a href="#">Second Level Item</a></li>
                        <li>
                            <a href="#">Second Level Item</a></li>
                        <li>
                            <a href="#">Second Level Item</a></li>
                    </ul>
                </li>
                <li>

                    <a href="css_animation.html"><i class="fa fa-magic"></i> <span class="nav-label">CSS Animations </span><span class="label label-info pull-right">62</span></a>
                </li>
-->
                <li>
                    <a href=""><i class="fa fa-calendar"></i> <span class="nav-label">Event Calendar</span><span class="label label-warning pull-right">Locked</span></a>
                </li>
                <li>
                    <a href=""><i class="fa fa-magic"></i> <span class="nav-label">Customize</span><span class="label label-warning pull-right">Locked</span></a>
                </li>
                <li>
                    <a href=""><i class="fa fa-sliders"></i> <span class="nav-label">Settings</span><span class="label label-warning pull-right">Locked</span></a>
                </li>
                <li class="landing_link">
                    <a target="_blank" href="<%= page_path(@conn, :index)%>"><i class="fa fa-star"></i> <span class="nav-label">Landing Page</span> <span class="label label-warning pull-right"></span></a>
                </li>
                <li class="special_link">
                    <a href=""><i class="fa fa-database"></i> <span class="nav-label">Packages</span></a>
                </li>
            </ul>

        </div>
    </nav>

web/templates/layout/none.html.eex
<html lang="en">
  <!--// <head></head> -->
  <%= render Flexcility.LayoutView, "header.html", assigns %>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
<%= render @view_module, @view_template, assigns %>

<!--// Footer -->
<div class="hidden">
<%= render Flexcility.LayoutView, "footer.html", assigns %>
</div>
</html>

web/templates/layout/organisation_layout.html.eex
<!doctype html>
<html lang="en">
 <%= render Flexcility.LayoutView, "header.html", assigns %>
<body>
	<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
	<script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
	<div class="wrapper">

		<!--// The menu bar on the left -->
		<%= render Flexcility.LayoutView, "organisation_sidebar.html", assigns %>

		<!--// The Main Panel (Exclusing the entire left menu bar -->
    <div class="main-panel">

			<!--// The top bar with the menu minimize button , search bar and
			notifications and Logout -->
			<%= render Flexcility.LayoutView, "organisation_top_navbar.html", assigns %>

      <!--// Template content -->
      <%= render @view_module, @view_template, assigns %>

			<!--// Footer -->
			<%= render Flexcility.LayoutView, "footer.html", assigns %>
    </div>
	</div>
</body>

web/templates/layout/organisation_sidebar.html.eex
<div class="organisation-sidebar sidebar" data-background-color="black" data-active-color="success">

<!--
Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
-->

  <div class="organisation-sidebar  sidebar-wrapper">
        <div class="logo dropdown">
          <a href="#" class="dropdown-toggle simple-text antique-white" data-toggle="dropdown">
            <div class="logo-organisation-layout"><img src="<%= image(@conn.assigns.current_organisation) %>" width="50px;" height="50px;" class="img-responsive"></div>
            <div class="logo-title-organisation-layout">
              <%= @conn.assigns.current_organisation.subdomain %>
            </div>
            <b class="caret"></b>
            </a>
            <ul class="flex-dropdown-menu dropdown-menu">
              <li><a href="#">Switch Organisation</a></li>
            </ul>
        </div>
        <div class="row">
          <div class="col-xs-11">
            <div class="sidebar-avatar col-xs-3">
                <div class="avatar">
                    <img src="<%= thumb(@current_user.profile) %>" alt="Circle Image" class="img-circle img-no-padding img-responsive">
                </div>
            </div>
            <div class="col-xs-8">
                <%= @current_user.profile.full_name || "Anonymous" %>
                <br />
                <span class="text-success"><small><%= link "Logout", to: session_path(@conn, :delete) %></small></span>
            </div>
          </div>
            <!-- <div class="col-xs-3 text-right">
                <btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-envelope"></i></btn>
            </div> -->
        </div>
        <ul class="nav antique-white">
            <li class="active">
                <a href="dashboard.html">
                    <i class="ti-panel"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li>
                <a href="user.html">
                    <i class="ti-user"></i>
                    <p>User Profile</p>
                </a>
            </li>
            <li>
                <a href="table.html">
                    <i class="ti-view-list-alt"></i>
                    <p>Table List</p>
                </a>
            </li>
            <li>
                <a href="typography.html">
                    <i class="ti-text"></i>
                    <p>Typography</p>
                </a>
            </li>
            <li>
                <a href="icons.html">
                    <i class="ti-pencil-alt2"></i>
                    <p>Icons</p>
                </a>
            </li>
            <li>
                <a href="maps.html">
                    <i class="ti-map"></i>
                    <p>Maps</p>
                </a>
            </li>
            <li>
                <a href="notifications.html">
                    <i class="ti-bell"></i>
                    <p>Notifications</p>
                </a>
            </li>

        </ul>
  </div>
</div>

web/templates/layout/sidebar.html.eex
<div class="sidebar" data-background-color="white" data-active-color="danger">

<!--
Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
-->

  <div class="sidebar-wrapper">
        <div class="logo dropdown">
          <div class="row">
              <div class="sidebar-avatar col-xs-3">
                  <div class="avatar">
                      <img src="<%= thumb(@current_user.profile) %>" alt="Circle Image" class="img-circle img-no-padding img-responsive">
                  </div>
              </div>
              <div class="col-xs-8">
                  <%= @current_user.full_name || "Anonymous" %>
                  <br />
                  <span class="text-success"><small><%= link "Logout", to: session_path(@conn, :delete) %></small></span>
              </div>

              <!-- <div class="col-xs-3 text-right">
                  <btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-envelope"></i></btn>
              </div> -->
          </div>
        </div>
        <div class="logo logo-mini">
          <!-- <div class="row"> -->
              <div class="user">
                  <div class="photo animated fadeInLeft">
                      <img src="<%= thumb(@current_user.profile) %>" alt="Circle Image" class="img-circle img-no-padding img-responsive">
                  </div>
              </div>
        </div>
        <ul class="nav">
            <li class="active">
                <a href="<%= organisation_path(@conn, :index) %>">
                    <i class="ti-view-grid"></i>
                    <p>Organisations</p>
                </a>
            </li>
            <li>
                <a href="user.html">
                    <i class="ti-user"></i>
                    <p>User Profile</p>
                </a>
            </li>
            <li>
                <a href="table.html">
                    <i class="ti-view-list-alt"></i>
                    <p>Table List</p>
                </a>
            </li>
            <li>
                <a href="typography.html">
                    <i class="ti-text"></i>
                    <p>Typography</p>
                </a>
            </li>
            <li>
                <a href="icons.html">
                    <i class="ti-pencil-alt2"></i>
                    <p>Icons</p>
                </a>
            </li>
            <li>
                <a href="maps.html">
                    <i class="ti-map"></i>
                    <p>Maps</p>
                </a>
            </li>
            <li>
                <a href="notifications.html">
                    <i class="ti-bell"></i>
                    <p>Notifications</p>
                </a>
            </li>

        </ul>
  </div>
</div>

web/templates/layout/top_navbar.html.eex
<nav class="navbar navbar-default">
  <div class="container-fluid navbar-flex-container">
    <div class="navbar-minimize">
      <button id="minimizeSidebar" class="btn btn-fill btn-icon"><i class="ti-more-alt"></i></button>
    </div>
    <div class="navbar-header">
        <button type="button" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar bar1"></span>
            <span class="icon-bar bar2"></span>
            <span class="icon-bar bar3"></span>
        </button>
        <a class="navbar-brand" href="#"><%= page_title @conn %></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="ti-panel"></i>
            <p>Stats</p>
          </a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="ti-bell"></i>
            <p class="notification">5</p>
            <p>Notifications</p>
            <b class="caret"></b>
          </a>
          <ul class="flex-dropdown-menu dropdown-menu">
            <li><a href="#">Notification 1</a></li>
            <li><a href="#">Notification 2</a></li>
            <li><a href="#">Notification 3</a></li>
            <li><a href="#">Notification 4</a></li>
            <li><a href="#">Another notification</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="ti-settings"></i>
            <p>Manage</p>
            <b class="caret"></b>
          </a>
          <ul class="flex-dropdown-menu dropdown-menu">
            <li><a href="#">My Profile</a></li>
            <li><a href="<%= organisation_path(@conn, :index) %>">My Organisations</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>