web/router.ex
defmodule Flexcility.Router do
  use Flexcility.Web, :router
  use Passport

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :current_user
  end

	pipeline :no_layout do
		plug :put_layout, false
	end

  pipeline :set_menu do
    plug Flexcility.Plugs.MenuItems
  end

  pipeline :redirect_logged_in_user do
    plug Flexcility.Plugs.RedirectLoggedInUser
  end

  pipeline :authorize do
    plug Flexcility.Plugs.Authorize
  end

  pipeline :load_profile do
    plug Flexcility.Plug.LoadProfile
  end

  scope "/", Flexcility do
    pipe_through [:browser]
    get "/logout", SessionController, :delete
    get "/not_found", PageController, :subdomain_not_found
    get "/error", PageController, :error
  end

  scope "/", Flexcility do
    pipe_through [:browser, :set_menu, :authorize]
    resources "/profiles", ProfileController, only: [:new, :create]
  end

  scope "/", Flexcility do
    pipe_through [:browser, :redirect_logged_in_user]
    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/forget-password", PasswordController, :forget_password
    post "/reset-password", PasswordController, :reset_password
  end

  scope "/", Flexcility do
    pipe_through [:browser, :set_menu, :authorize, :load_profile] # Use the default browser stack

    get "/send_email_test", OrganisationController, :send_an_email
    resources "/organisations", OrganisationController do
      get "/manage", Organisation.ManagementController, :index
      scope "/manage" do
        resources "/traits", Organisation.TraitController, except: [:update, :create]
        put "/traits", Organisation.TraitController, :update
        get "/members", Organisation.ManagementController, :members
        resources "/sites", Organisation.SiteController do
          resources "/assets", Organisation.AssetController
        end
      end
    end
    resources "/sites", SiteController do
      resources "/assets", AssetController
      post "/invite_user", SiteController, :invite_user, as: :invite
    end
    resources "/requests", RequestController do
      get "/assign_technicians", RequestController, :assign_technicians, as: :assign_technicians
      post "/assign_technicians", RequestController, :create_technician_assignment, as: :assign_technicians
    end

    resources "/orders", OrderController do
      get "/assign_technicians", OrderController, :assign_technicians, as: :assign_technicians
      post "/assign_technicians", OrderController, :create_technician_assignment, as: :assign_technicians
    end
    resources "/reports", ReportController
    get "/profiles/edit", ProfileController, :edit
    resources "/profiles", ProfileController, except: [:index, :new, :create]
    resources "/invitations", InvitationController do
      get "/accept", InvitationController, :view_invite, as: :view
      post "/accept", InvitationController, :accept_invite, as: :accept
    end
  end


  scope "/api", Flexcility, as: :api do
    pipe_through [:api, :set_menu]
    resources "/organisations", Api.OrganisationController, only: [:create]
    resources "/sites", SiteController, only: [] do
      get "/assets", AssetController, :index
      resources "/assets", Api.AssetsController, except: [:new, :edit]
    end
    get "/subdomain_unique", OrganisationController, :subdomain_unique
  end

  if Mix.env == :dev do
  # If using Phoenix
  forward "/sent_emails", Bamboo.EmailPreviewPlug

end


  # Other scopes may use custom stacks.
  # scope "/api", Flexcility do
  #   pipe_through :api
  # end
end

web/subdomain_router.ex
defmodule Flexcility.SubdomainRouter do
  use Flexcility.Web, :router
  use Passport

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :current_user
    plug :put_layout, {Flexcility.LayoutView, :organisation_layout}
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :current_user
  end

  pipeline :no_layout do
    plug :put_layout, "none.html"
  end

  pipeline :set_menu do
    plug Flexcility.Plugs.MenuItems
  end

  pipeline :redirect_logged_in_user do
    plug Flexcility.Plugs.RedirectLoggedInUser
  end

  pipeline :authorize do
    plug Flexcility.Plugs.Authorize
    plug Flexcility.Plugs.AuthorizeForOrganisation
  end

  pipeline :load_profile do
    plug Flexcility.Plug.LoadProfile
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :authorize, :load_profile] # Use the default browser stack
    # get "/", DashboardController, :index
    get "/dashboard", DashboardController, :index
    get "/profile", ProfileController, :show
    put "/profile", ProfileController, :update
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :no_layout]
    get "/logout", SessionController, :delete
    get "/invitations/:invitation_key", InvitationController, :show
    post "/invitations/:invitation_key/accept", InvitationController, :accept
    post "/invitations/:invitation_key/reject", InvitationController, :reject
  end

  scope "/", Flexcility.Subdomain do
    pipe_through [:browser, :redirect_logged_in_user]
    get "/login", SessionController, :new
    get "/", SessionController, :new
    get "/login/:invitation_key", SessionController, :invitation
    post "/login", SessionController, :create
  end

  scope "/", Flexcility do
    pipe_through [:browser]
    get "/register", RegistrationController, :invitation
    post "/register", RegistrationController, :create
  end
  #
  # scope "/", Flexcility.Subdomain do
  #   pipe_through [:browser, :redirect_logged_in_user]
  #   get "/register", RegistrationController, :new
  #   post "/register", RegistrationController, :create
  #   get "/forget-password", PasswordController, :forget_password
  #   post "/reset-password", PasswordController, :reset_password
  # end



  # Other scopes may use custom stacks.
  # scope "/api", Flexcility do
  #   pipe_through :api
  # end
end

web/models/report.ex
defmodule Flexcility.Report do
  use Flexcility.Web, :model

  schema "reports" do
    field :title, :string
    field :description, :string
    field :location, :string
    field :type, :string
    field :instruction, :string
    field :priority, :string
    field :deadline, :string
    field :findings, :string
    field :actions, :string
    field :summary, :string
    field :completed, :string

    belongs_to :user, Flexcility.User
    belongs_to :order, Flexcility.Order

    has_many :assigned_technicians, Flexcility.AssignedTechnician

    timestamps
  end

  @required_fields ~w(title description location instruction priority actions summary completed order_id)
  @optional_fields ~w(type deadline findings)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end

  def create_changeset(model, user_id, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> put_user_id(user_id)
  end

  def put_user_id(changeset, user_id) do
    case changeset do
      %Ecto.Changeset{valid?: true} ->
        put_change(changeset, :user_id, user_id)
      _ ->
        changeset
    end
  end

  def put_order_id(changeset, order_id) do
    case changeset do
      %Ecto.Changeset{valid?: true} ->
        put_change(changeset, :order_id, order_id)
      _ ->
        changeset
    end
  end

  def with_owner(query) do
    from q in query, preload: [:user]
  end
end

web/controllers/report_controller.ex
defmodule Flexcility.ReportController do
  use Flexcility.Web, :controller

  alias Flexcility.Report
  alias Flexcility.Order
  alias Flexcility.Request

  plug :scrub_params, "report" when action in [:create, :update]

  def index(
    %{assigns: %{current_user: current_user}}=conn, _params
  ) do
    user = current_user |> Repo.preload([:reports])
    reports = user.reports
    render(conn, "index.html", reports: reports)
  end

  def new(conn, %{"order_id" => order_id}) do
    order_fields = [:request_id, :order_id, :title, :description, :location, :type, :instruction, :priority, :inserted_at, :deadline]

    {order_attributes, _} = Repo.get(Order, order_id)
                          |> Map.from_struct
                          |> Map.split(order_fields)

    changeset = Report.changeset(%Report{}, order_attributes)
    render(conn, "new.html", changeset: changeset, order_id: order_id)
  end

  def create(conn, %{"report" => report_params}) do
    current_user = conn.assigns.current_user
    changeset = Report.create_changeset(%Report{}, current_user.id, report_params)

    case Repo.insert(changeset) do
      {:ok, _report} ->
        conn
        |> put_flash(:info, "Report created successfully.")
        |> redirect(to: report_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    report = Repo.get!(Report, id)
    report = Report |> Report.with_owner |> Repo.get!(id)
    render(conn, "show.html", report: report)
  end

  def edit(conn, %{"id" => id}) do
    report = Repo.get!(Report, id)
    changeset = Report.changeset(report)
    render(conn, "edit.html", report: report, changeset: changeset, order_id: changeset.model.order_id)
  end

  def update(conn, %{"id" => id, "report" => report_params}) do
    report = Repo.get!(Report, id)
    changeset = Report.changeset(report, report_params)

    case Repo.update(changeset) do
      {:ok, report} ->
        conn
        |> put_flash(:info, "Report updated successfully.")
        |> redirect(to: report_path(conn, :show, report))
      {:error, changeset} ->
        render(conn, "edit.html", report: report, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    report = Repo.get!(Report, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(report)

    conn
    |> put_flash(:info, "Report deleted successfully.")
    |> redirect(to: report_path(conn, :index))
  end
end

web/views/report_view.ex
defmodule Flexcility.ReportView do
  use Flexcility.Web, :view
  import Flexcility.RequestView, only: [asset_name: 1, project_name: 1]
  import Flexcility.LayoutView, only: [display_name: 1, image: 1, profile_image: 1]

    # Takes a users_roles struct that has role.name = "Admin" and returns
    # %{user: <the matched user>, role: "Admin"}
    def admins(%{role: %{name: "Admin"}, user: admin}) do
        %{user: admin, role: "Admin"}
    end

    def admins(_) do
      []
    end

    def technicians(technician) do
        %{user: technician, role: "Technician"}
    end

    def technicians(_) do
      []
    end

    # Calls `admins` from above to get a list of admins and roles,
    # i.e. [%{user: <admin struct>, role: "Admin"}]
    def admins_with_roles(project_roles) do
      project_roles
      |> Enum.map(&admins/1)
    end

    # All orders/requests have an owner, so we don't ned to match for _
    # like technicians and admins
    def owner_with_roles(owner) do
      %{user: owner, role: "Requestor"}
    end

    # Sites also MUST have owner, so no need to match for _
    def project_owner_with_roles(project_owner) do
      %{user: project_owner, role: "Site Owner"}
    end

    # Calls `technicians` to get a  list of technicians and roles,
    # i.e. [%{user: <admin struct>, role: "Technician"}]
    def technicians_with_roles(assigned_technicians) do
      assigned_technicians
      |> Enum.map(&technicians/1)
    end

    @doc ~S"""
    Returns a map of users and roles, grouped by user.
    Looks like this:
     %{<user A> => [%{user: <user A>, role: "Admin"}],
       <User B> => [%{user: <User B>, role: "Admin"},
                    %{user: <User B>, role: "Technician"}],
       <User C> => [%{user: <User C, role: "Client"}]
       ... and so on
      }


      Note: a fully preloaded user struct with no associations looks like this:
      %Flexcility.User{__meta__: #Ecto.Schema.Metadata<:loaded>,
       assigned_orders: [],
       assigned_requests: []>,
       assigned_technicians: [],
       attached_sites: [],
       email: "fadhil@jomcode.com", first_name: "Fadhil", id: 3,
       inserted_at: #Ecto.DateTime<2016-07-26T15:56:24Z>, last_name: "Luqman",
       orders: []>,
       password: nil, password_confirmation: nil,
       password_hash: "$2b$12$3kX9.T4nOinKtD6buN0G8.N2YCQXmBfDa.gJSlLjNrE8iZDLnUzzq",
       sites: []>,
       reports: [],
       requests: [],
       roles: [],
       updated_at: #Ecto.DateTime<2016-07-28T04:12:06Z>,
       users_roles: []}
    """
    def members_and_roles(%{user: owner,
                            technicians: assigned_technicians,
                            request: %{
                              site: %{
                                user: project_owner,
                                users_roles: project_roles                            }
                            }
                          }) do # Here we match an order that's been preloaded
                                # with these associations

      # Now we put them together and flatten them, and then group by user struct
      members = [admins_with_roles(project_roles),
                 owner_with_roles(owner),
                 project_owner_with_roles(project_owner),
                 technicians_with_roles(assigned_technicians)
                ]
                |> List.flatten
                |> Enum.group_by(fn m -> m.user end)
    end

    # Gets a list or user and roles,
    #  e.g. [{user: <user A>, role: "Admin"},
    #        {user: <user A>, role: "Technician"}]
    # and returns all the roles in a comma separated list, e.g. "Admin, Technician"
    def display_roles(member_roles) do
      member_roles
      |> Enum.map(fn mr -> mr.role end)
      |> Enum.join(",")
    end

end

web/templates/report/edit.html.eex
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Edit Report <small></small></h5>
        </div>
          <%= render "form.html", changeset: @changeset,
            action: report_path(@conn, :update, @report),
            order_id: @order_id,
            conn: @conn %>
      </div>
    </div>
  </div>
</div>

web/templates/report/form.html.eex
<div class="ibox-content">
  <%= form_for @changeset, @action, [multipart: true, class: "form-horizontal"], fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
    <% end %>

    <div class="form-group">
      <%= label f, :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_input f, :title, class: "form-control" %>
        <span class="error-tag">
        <%= error_tag f, :title %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= textarea f, :description, class: "form-control" %>
        <span class="error-tag">
        <%= error_tag f, :description %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, :location, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_input f, :location, class: "form-control" %>
        <span class="error-tag">
        <%= error_tag f, :location %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, :type, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_input f, :type, class: "form-control" %>
        <span class="error-tag">
        <%= error_tag f, :type %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, :instruction, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= textarea f, :instruction, class: "form-control" %>
        <span class="error-tag">
        <%= error_tag f, :instruction %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, :priority, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_input f, :priority, class: "form-control" %>
        <span class="error-tag">
        <%= error_tag f, :priority %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, :deadline, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_input f, :deadline, class: "form-control" %>
        <span class="error-tag">
        <%= error_tag f, :deadline %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, :findings, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= textarea f, :findings, class: "form-control" %>
        <span class="error-tag">
        <%= error_tag f, :findings %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, :actions, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= textarea f, :actions, class: "form-control" %>
        <span class="error-tag">
        <%= error_tag f, :actions %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, :summary, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= textarea f, :summary, class: "form-control" %>
        <span class="error-tag">
        <%= error_tag f, :summary %>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= label f, :completed, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= text_input f, :completed, class: "form-control" %>
        <span class="error-tag">
        <%= error_tag f, :completed %>
        </span>
      </div>
    </div>

  <%= hidden_input f, :order_id, value: @order_id  %>

  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
    <%= submit "Submit", class: "btn btn-primary btn-rounded" %>
    <%= link "Back", to: report_path(@conn, :index), class: "btn btn-default btn-outline btn-rounded" %>
    </div>
  </div>
  <% end %>
</div>

web/templates/report/index.html.eex
<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInUp">

      <div class="ibox">
        <div class="ibox-title">
          <h2>All Reports</h2><h5>Assigned to <!-- display_name(@current_user) --></h5>
          <div class="ibox-tools">
            <a href="" class="btn btn-white btn-rounded btn-outline btn-sm">Locked</a>
            <!-- Reserve for future link -->
          </div>
        </div>
        <div class="ibox-content">
          <div class="project-list">

            <table class="table table-hover">
              <tbody>
                <%= for report <- @reports do %>
                  <%= link to: report_path(@conn, :show, report) do %>
                  <tr>
                    <td class="project-status">
                      <span class="label label-success"><!-- request.id --></span>
                    </td>
                    <td class="project-title">
                      <a href="<%= report_path(@conn, :show, report) %>"><%= report.title %>
                      <br/>
                      <small class="created-on">By <!-- display_name(report.user) --> on <%= report.inserted_at %></small>
                      </a><!-- To be replaced with display_created_at(report) -->
                    </td>
                    <td class="hidden-xs"><%= report.location %></td>
                    <td class="hidden-xs"><%= report.description %></td>
                    <td class="project-people">
                      <a href=""><img alt="image" class="img-circle" src="img/a3.jpg"></a>
                      <a href=""><img alt="image" class="img-circle" src="img/a1.jpg"></a>
                      <a href=""><img alt="image" class="img-circle" src="img/a2.jpg"></a>
                      <a href=""><img alt="image" class="img-circle" src="img/a4.jpg"></a>
                      <a href=""><img alt="image" class="img-circle" src="img/a5.jpg"></a>
                    </td>
                    <td class="project-actions">
                      <%= link to: report_path(@conn, :show, report), class: "btn btn-white btn-rounded btn-sm" do %>
                        <i class="fa fa-folder"></i> View </a>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>

          </div> <!-- End project-list -->
        </div> <!-- End ibox-content -->
      </div> <!-- End ibox -->

    </div> <!-- End wrapper -->
  </div> <!-- End col -->
</div> <!-- End row -->

web/templates/report/new.html.eex
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Create A New Report <small></small></h5>
        </div>
        <%= render "form.html", changeset: @changeset,
          action: report_path(@conn, :create),
          order_id: @order_id,
          conn: @conn %>
      </div>
    </div>
  </div>
</div>

web/templates/report/show.html.eex
<div class="row">
  <div class="col-lg-9">
    <div class="wrapper wrapper-content animated fadeInUp">
      <div class="ibox">
        <div class="ibox-content">
          <div class="row">
            <div class="col-lg-12">
              <div class="m-b-md">
                <%= link "Back", to: report_path(@conn, :index),
                class: "btn btn-default btn-outline btn-rounded btn-sm pull-right" %>
                <%= link "Edit Report", to: report_path(@conn, :edit, @report),
                class: "btn btn-warning btn-rounded btn-sm pull-right" %>


            <h2><%= @report.title %></h2>
          </div>
              <dl class="dl-horizontal">
                <dt>Location:</dt>
                <dd>
                  <span>
                    <%= @report.location %>
                  </span>
                </dd>
                <dt>Description</dt>
                <dd>
                  <span>
                    <%= @report.description %>
                  </span>
                </dd>
              </dl>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <dl class="dl-horizontal">

                <dt>Owner:</dt> <dd><%= display_name(@report.user) %></dd>
                </dd>
              </dl>
            </div>


            <div class="col-lg-6" id="cluster_info">
              <dl class="dl-horizontal" >

                <dt>Last Updated:</dt> <dd><%= @report.updated_at %></dd>
                <dt>Created:</dt> <dd><%= @report.inserted_at %> </dd>

              </dl>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12">
              <dl class="dl-horizontal">
                <dd>
                  <%= link "Assign Technicians", to: order_assign_technicians_path(@conn, :assign_technicians, @report.id), class: "btn btn-success btn-rounded" %>
              </dl>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="wrapper wrapper-content project-manager">
      <h3>Asset</h3>
      <img src="<%=# image(@site) %>" class="img-responsive">
      <p class="small">

      </p>
      <h5>Model</h5>
      <p class="small"></p>
      <h5>Location</h5>
      <p class="small"><%= @report.location%></p><br/>
      <br/>
      <h3>Site</h3>
      <img src="<%=# image(@site) %>" class="img-responsive">
      <p class="small">

      </p>
      <h5>Address</h5>
      <p class="small"></p>
    </div>
  </div>
</div>